### PR TITLE
Add gradle build script

### PR DESCRIPTION
**Pull request by nishtahir**
Added Gradle build script for issue #1

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks for this. I don't know gradle very well, but this seems very excessive. Should all of this be tracked? 
Is this what you had in mind @ftomassetti?

**Comment by nishtahir** [comment]
This is pretty standard for Gradle builds. I updated the `.gitignore` to exclude the necessary files already. 

Allow me to elaborate on what the various files do,

The `build.gradle` file is the actual build script analogous to the `pom.xml` file in maven. 
The `gradlew` and `gradlew.bat` files are [gradle wrapper scripts](https://docs.gradle.org/current/userguide/gradle_wrapper.html), that basically function as embedded gradle distribution which allow contributors to the project to basically use the exact same version of gradle without needing to have a local gradle install. There is something similar available for maven known as the [maven wrapper](https://github.com/takari/maven-wrapper). The other files are simply config files.

**Comment by ftomassetti** [comment]
Hi David, it seems ok with me. Is indeed typical to include in projects using gradle the gradle wrappers. In practice they are scripts which can install gradle for you, if you do not have it in your system. This is particularly cool because in this way the whole project is self-contained.

I personally prefer Gradle and I like this PR, but it is true that in the project we have the pom (for Maven). Should we have two different distributions? Two separate branches? Or just one repository with both Maven and Gradle?

**Comment by tipsy** [comment]
> The gradlew and gradlew.bat files are gradle wrapper scripts, that basically function as embedded gradle distribution which allow contributors to the project to basically use the exact same version of gradle without needing to have a local gradle install. 

Thanks, that helps!

> I personally prefer Gradle and I like this PR, but it is true that in the project we have the pom (for Maven). Should we have two different distributions? Two separate branches? Or just one repository with both Maven and Gradle?

I'm feeling pretty lazy today, and maintaining two branches is more work... If they can co-exist peacefully in the one branch then I'd rather just merge it as is. It would be nice if we could group it together in a gradle-dir, but I'm guessing that's not possible?

**Comment by nishtahir** [comment]
They can coexist without an issue. 

> It would be nice if we could group it together in a gradle-dir, but I'm guessing that's not possible?

The files are usually in the project root. 😕

**Comment by tipsy** [comment]
> The files are usually in the project root. :confused: 

Yup. It will be slightly messy, but I think it's okay. Thanks for your work :)

**Pull request merged**
